### ISSUE TITLE
R Version

### ISSUE THREAD

**Issue by oganm** [drsimonj/corrr#25]
Just wanted to report that all tests and vignettes work fine in R version 3.1.2. While I see that is not sufficient motivation to reduce the tried and true required version number, there are people out there who cannot update their R versions for a variety of reasons. So if you would be willing to do that I am sure you will appease some. A workaround is to fork and change the required version number.

**Comment by igordot** [comment]
I agree. If not 3.1.2, at least 3.3.0. I tried installing the oldest archived version (0.1.0) and even that one required 3.3.1.

The commit where R was changed from 3.3.0 to 3.3.1 doesn't seem to contain any other changes that would warrant that.

**Comment by drsimonj** [comment]
I develop using 3.3.1, so wanted to be safe. Now I can see a desire for relaxed dependency (and thanks to you both for engaging), I'm happy to drop to 3.3.0 (after local testing). Will commit in a second.
