### ISSUE TITLE
Feature request: arithmetic with correlation data frames

### ISSUE THREAD

**Issue by jcberny** [drsimonj/corrr#26]
Showing which correlations change between treatments would be of great use. Is there a way to subtract one correlation data frame of one treatment with the other treatment, and still be in a object class that corrr can plot?

**Comment by drsimonj** [comment]
This should be extended to accommodate any sort of matrix algebra that makes sense in the context of correlation data frames. For example, given two correlation data frames, `r1` and `r2`, it'd be nice to be able to do the following while preserving the `cor_df` class:

```
r1 + r2

r1 - r2

r1 * r2

r1 / r2
```

Other considerations might be:

```
r1^2
```
