### ISSUE TITLE
`focus_if` as method to focus on variables that meet certain criteria.

### ISSUE THREAD

**Issue by JSmith11** [drsimonj/corrr#30]
Hi,

I am trying to use `dplyr` with `corrr`. I have opened a question in [Stackoverflow](http://stackoverflow.com/questions/40564646/specifying-correlation-strength-prior-to-plotting-using-corrr?noredirect=1#comment68367955_40564646) and was advised to go here for an answer or to report a bug (to be honest I'm not sure if it is a bug)

I have a data frame of correlations where I'm trying to only show the correlations above 10% I want to then plot this using the corrr package

I take the correlation of my data set, then filter to where the absolute value is >.1 but it fails on the network plot segment
> Error in UseMethod("network_plot") : no applicable method for 'network_plot' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

A reproducible example is below. Thank you for your time and for investing in such a useful package

```
library(tidyverse)
library(corrr)

# Create the Dataframe
mydf <- data.frame(a=sample(rnorm(n = 100,sd = 15),replace=TRUE),
                   b=sample(rnorm(n = 100,sd = 15),replace=TRUE),
                   c=sample(rnorm(n = 100,sd = 15),replace=TRUE),
                   d=sample(rnorm(n = 100,sd = 15),replace=TRUE),
                   e=sample(rnorm(n = 100,sd = 15),replace=TRUE),
                   f=sample(rnorm(n = 100,sd = 15),replace=TRUE))


test <- mydf %>% 
  correlate(method = "spearman") %>% 
  gather("n", "corr", 2:7, na.rm = TRUE) %>% 
  filter(abs(corr) > 0.1) %>% 
  spread(rowname,corr) %>%
  network_plot(legend = TRUE)
```

**Comment by drsimonj** [comment]
Hi there,

Thanks again for writing and I hope the solution on StackOverflow helped.
Thanks for adding the issue on GitHub too! I'll see what I can do about it.
I haven't had a chance to do much work on corrr lately, but I'm hoping I'll
have plenty of time in the coming months.

Please let me know if you have any further trouble.

Very best,

Simon

**Comment by drsimonj** [comment]
Re [stackoverflow](http://stackoverflow.com/a/40569507/6447662) comment, the problem I see it is to focus the correlation data frame on a set of variables that correlate more than some value with at least one other variable.

A general extension of this might be a special implementation of `focus(mirror = TRUE)` that takes a condition to apply to each correlation column. Maybe, similar to `dplyr::mutate_if`, there could be `focus_if`. This applies a function to all correlation columns and adds them to focus if TRUE. `mirror` argument can remain optional.

So, to solve the original problem, there'd be something like:

```
mtcars %>% correlate() %>% focus_if(.f, mirror = TRUE) %>% network_plot()
````

where `.f` is a function that finds columns with a correlation greater than .1.

**Comment by JSmith11** [comment]
Hi,

That actually looks great and would a very elegant solution
If you would like me to test it if you implement it, please let me know. I would be happy to help

Thanks again for your time

**Comment by drsimonj** [comment]
Great, thanks @JSmith11. I'll let you know. Now I just need to find the time! Hopefully it shouldn't be too challenging.

**Comment by drsimonj** [comment]
@JSmith11 if you can, install the latest dev version of corrr and try `focus_if`. There are some docs that should help (`?focus_if`). Let me know how you go.

**Comment by JSmith11** [comment]
Hi Simon [@drsimonj<https://github.com/drsimonj>]

Sorry for the delay in getting back to you. The week has been a bit manic with deadlines
I gave it a go but couldn’t get it to work (more owing to my R skills than anything else, I suspect)

    any_greater_than <- function(x, val) {
      mean(abs(x), na.rm = FALSE) > val
    }

    test <- mydf %>%
      select(1:4) %>%
      correlate(method = "spearman") %>%
      focus_if(any_greater_than, .6) %>%
      network_plot()


Ø  Error in as_cordf(rdf) : Input object x is not a square. The number of columns must be equal to the number of rows.

However I did manage to create what I was looking for by mangling some code together

    library(tidyverse)
    library(corrr)
    mydf <- iris

    test <- mydf %>%
      select(1:4) %>%
      correlate(method = "spearman")

    # Create the correlation Matrix cutoff
    test <- as.data.frame(test)
    test[is.na(test)] <- 0
    test[test < 0.6] <- 0

    # Generate the plot
    test[, 2:5] %>%
      network_plot()

Thanks

**Comment by drsimonj** [comment]
Thanks for testing it, @JSmith11 .
My guess is that you need to add `mirror = TRUE` as an argument. I.e., to write `focus_if(any_greater_than, .6, mirror = TRUE)`. Try it out and let me know how you go.

To explain a bit...
When `mirror = FALSE` (which is default), any `focus` function will select your variables into the columns, but remove them from the rows. The result is, therefore, NOT a complete set of correlations.  This removes the `cor_df` class because of it. By specifying `mirror = TRUE`, the variables you select into column are also kept in the rows, and everything else is removed. The result IS a complete correlation data frame which can be plotted.

**Comment by JSmith11** [comment]
Ah, makes sense

I tried it with the code below

library(tidyverse)
library(corrr)

mydf <- iris


any_greater_than <- function(x, val)
  {
  mean(abs(x), na.rm = FALSE) > val
  }

mydf %>% select(1:4) %>%
  correlate(method = "spearman") %>%
  focus_if(any_greater_than, 0.3, mirror = TRUE) %>%
  network_plot()

And got the following


Ø  Error in focus_if.cor_df(., any_greater_than, 0.3, mirror = TRUE) :

  No variables were TRUE given the function.


This doesn’t seem to be the case as petal length and sepal length are above .8

**Comment by drsimonj** [comment]
This is because of `any_greater_than`. As is, it will search for any variables that have a **`mean`** correlation with other variables greater than some value. It sounds like you want to find variables that have any correlation greater than some value with For this, use:

```r
any_greater_than <- function(x, val) { 
  any(abs(x) > val)
} 
```

Aside, once this works, you might run into a `network_plot` error about `GeomTextRepel`. I'm about to fix it. But if you get it, set `network_plot(repel = TRUE)` for now.

**Comment by JSmith11** [comment]
Hi

This is great, works like a charm
I didn’t encounter the `GeomTextRepel` error at all ☺

Thank you again for your help. I have saved the R Script in my library and this is going to be “my go” to for future correlation visualizations ☺

**Comment by drsimonj** [comment]
Glad to hear it 👍
