### ISSUE TITLE
Straight lines in the network plot

### ISSUE THREAD

**Issue by jcberny** [drsimonj/corrr#33]
Hi Simon, 
Just wondering if it would be possible to have the option in the future to make the connecting lines straight instead of round in the network plot.

**Comment by drsimonj** [comment]
Certainly. I've got a few other features and bugs to get through with little time, but I did have something like this in mind too. Will get to it ASAP.

**Comment by drsimonj** [comment]
You can now do `network_plot(curved = FALSE)` to get straight lines.

**Comment by jcberny** [comment]
Hi, thanks a lot. However I'm getting the following error message:
Error: GeomTextRepel was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.

Would I need to use a specific version of ggplot2?

**Comment by drsimonj** [comment]
Latest ggplot2 version (2.2.0) has led to this error. I've logged it but not found a solution yet (see #32 ).

For now, try to also add `repel = FALSE` as an argument. This will avoid using GeomTextRepel

**Comment by jcberny** [comment]
repel = F does work. Thanks!

**Comment by drsimonj** [comment]
Great :)
Now if I could just solve #32 !
