### ISSUE TITLE
Dealing with missing values

### ISSUE THREAD

**Issue by tomsing1** [drsimonj/corrr#38]
Great package! Just curious: you chose to make `use = pairwise.complete.obs` the default for the `correlate` function. That approach is not without problems, see e.g. B.W. Lewis' examples [here](http://bwlewis.github.io/covar/missing.html). Doesn't chosing `pairwise.complete.obs` as the default increase the risk that users won't even notice that they might have a problem? (Or that the might have NA values at all?)

**Comment by drsimonj** [comment]
Thanks @tomsing1 . This hasn't been a major problem for me in practice so my preference is to keep `use = pairwise.complete.obs` by default.

However, I think it's a good point and to at least warn people. Perhaps the function could print a message about the method and provide a boolean `quiet` argument. E.g.,:


```r
correlate <- function(x, y = NULL,
                       use = "pairwise.complete.obs",
                       method = "pearson",
                      diagonal = NA,
                      quiet = FALSE) {
  x <- stats::cor(x = x, y = y, use = use, method = method)

 if (!quiet) message("Using method", method)

  as_cordf(x, diagonal = diagonal)
}
```



Thoughts?

**Comment by tomsing1** [comment]
Thanks for thinking about it. I agree that it's not a major problem, but I like your idea of reminding people that it's a different default from that of the `cor()` function.

Your example is great, perhaps you want to include both the `method` and the `use` parameters in the message?

```
 if (!quiet) {
    message(paste("Using method", method, "with", use))
}
```

**Comment by drsimonj** [comment]
Oh yes, of course! I'll add it in.
