### ISSUE TITLE
rotating X-axis labels in Rplot

### ISSUE THREAD

**Issue by vertesy** [drsimonj/corrr#41]
Hello and thanks for this cool package! 

Following your 2017 lightning talk:

	corrr::correlate(mtcars[, 1:4], method = "pearson") %>%
	  corrr::rearrange(absolute=F) %>% #  rearrange cols and rows
	  corrr::shave()%>% # shave upper triangle
	  corrr::rplot(print_cor = T,legend = T)# dot plot

I get this graph. Now I want to do it on a larger dataset (59 columns), wtih long names (10-15 character).

![img](https://snag.gy/Pw3xhs.jpg)

**I did not find a way to rotate X-axis labels, so that the column names do not overlap and hide each other. Is it possible?**

thanks,
Abel

**Comment by vertesy** [comment]
My apologies, its the standard ggplot2 syntax

`rplot(print_cor = T,legend = T) + theme(axis.text.x = element_text(angle = 60, hjust = 1))`

**Comment by drsimonj** [comment]
Yep, that's it :)
