### ISSUE TITLE
Issue: dplyr mutate(), filter() and various other funs coerce "cor_df" to "tbl_df"

### ISSUE THREAD

**Issue by mdancho84** [drsimonj/corrr#43]
Just a heads up. I don't know if this is something you will want to consider, but if you try to filter() or mutate() objects with the "cor_df" class they will be coerced to "tbl_df". Here's the link that describes the issue and the resolution:

https://github.com/hadley/dplyr/issues/719

**Comment by drsimonj** [comment]
This gets at the thinking behind the groups of functions that corrr offers: those that make internal changes like `rearrange()` and `shave()`, which keep the cor_df class, and those that change the structure like `focus()` and `stretch()`, which drop this class.

This presents a challenge with dplyr functions, which can keep or alter the structure depending on how they're used. E.g., it's OK to keep class after `mutate()` if an existing column is changed, but not OK if a new column is added.

Can you think of a robust way to check when dplyr functions are used and the original structure is kept? If not, then probably safer to allow the class to be dropped.

The alternative is to generalise the corrr functions (which I started doing some time back). E.g., having a dataframe method for the corrr functions that attempt to coerce the object to a cor_df with `as_cordf()`, and then apply the cor_df method. Will have to check what needs updating on this front.

**Comment by mdancho84** [comment]
Here's how to do it for `mutate()`. The same procedure will need to be done for `filter()`, `slice()`, `gather()`, `spread()`, and `group_by()`. The only one that I'm unsure of how to handle is `group_by()`.

```
mutate_.cor_df <- function(data, ...) {
    # preserve cor_df meta data during mutate operations
    out <- data
    class(out) <- class(out)[-1]
    
    # perform tidyverse function
    out <- dplyr::mutate_(out, ...)
    
    # reapply class
    class(out) <- class(data)

    #reapply any special attributes if required (it didnt look like cor_df has any based on a cursory review)
    attr(out, "special_attr")     <- attr(data, "special_attr")
    return(out)
}
```

**Comment by drsimonj** [comment]
Nice solution. It doesn't quite deal with my concern about the need to keep/drop the "cor_df" class depending on whether the structure is preserved. Perhaps there's a way to check for this/coerce with `as_cordf()` somewhere within this?

**Comment by mdancho84** [comment]
I'm sure we can come up with a solution. What defines the `cor_df` structure? 

- n x n matrix
- one's in the diagonal
- has `cor_df` class

Each of these can be inspected / validated. If one isn't present then the `cor_df` class is not retained. Let me know if I'm missing any or if any assumptions are incorrect.

**Comment by drsimonj** [comment]
Given an object `d`, cor_df structure can be **minimally** validated with three conditions:

```r
is.data.frame(d)
all(c("rowname", d$rowname) == colnames(d))
all(purrr::map_lgl(d[-1], is.numeric))
```

This ensures that `d` is a data frame which has a "rowname" column followed by *n* numeric variables that are represented in an ordered way by "rowname".

Nonetheless, given further thought, I wonder what the use cases are? By using `mutate()`, you're changing the values and, thus, the correlations that corrr is helping you to explore. Can you think of cases in which you would `mutate()` a cor_df and still want to use cor_df methods?

`filter()` and `select()` are definitely out as they will always disrupt the cor_df structure (and why `focus(mirror = TRUE)` is available).

**Comment by mdancho84** [comment]
I agree. I know this issue is a potential problem, but is it truly a problem given how the functions and `cor_df` data structure will be used. Maybe we table this for now. If others find this to be an issue, it can always be revisited.

**Comment by drsimonj** [comment]
Agreed. I'll close this issue but can reopen if it comes up again. Thanks anyway for bringing it to my attention.
