### ISSUE TITLE
Border around circles as an option?

### ISSUE THREAD

**Issue by zx8754** [drsimonj/corrr#45]
Example:
```R
rplot(shave(correlate(mtcars)), legend = TRUE)
```

See `x=drat` and `y=carb`, it is invisible, of course it is almost transparent as there is no correlation. But it would be nice to have (as an option) a black circle around it to help with focusing on that spot?

Something like this:
```R
rplot(shave(correlate(mtcars)), legend = TRUE, border = TRUE, borderCol = "black")
```

**Comment by drsimonj** [comment]
Thanks for the suggestion. However, I think such tweaking is too detailed. The corrr plotting functions are available for fast exploration. For finely controlled plots, it's better to construct it yourself using ggplot2.

Take a look at how `rplot` works [here](https://github.com/drsimonj/corrr/blob/master/R/cor_df.R#L133-L183). You can probably reuse and adjust the code as needed.
