### ISSUE TITLE
Adding `cor_df` method for `fashion`

### ISSUE THREAD

**Issue by cimentadaj** [drsimonj/corrr#50]
After reading the docs of `fashion` I understand that it's not entirely made to work with a `cor_df` object and that's nice because you don't depend on it. However, there's no actual method for `cor_df`.

Perhaps it would be more consistent to add also `fashion.cor_df` that performs the same thing but preserves the `cor_df` and `tbl` classes for nicer printing and consistency within the pipeline.

```r
library(corrr)
#> Loading required package: dplyr
#> Warning: package 'dplyr' was built under R version 3.4.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
d <- correlate(mtcars)
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'

class(d)
#> [1] "cor_df"     "tbl_df"     "tbl"        "data.frame"

d %>% fashion() %>% class()
#> [1] "data.frame" "noquote"
```

**Comment by cimentadaj** [comment]
If it makes sense I could add it and issue a pull request.

**Comment by cimentadaj** [comment]
Aha, I've thought it through and found a reason why this might not make much sense. If `fashion` is the last step within a pipeline and it's purpose is simply for printing (usually for a paper or the like) then creating `frashion_cor_df` would just be for pure consistency but it doesn't really matter if it's a data frame or a tibble -- there's not further processing going on.

If that's the case then this shouldn't be priority at all.

**Comment by drsimonj** [comment]
Yes, you have come to the same answer I was going to give! Once you use fashion, the values are characters and it's not meaningful to operate on them anymore.
