### ISSUE TITLE
Create a DB backend

### ISSUE THREAD

**Issue by edgararuiz** [drsimonj/corrr#51]
Hi @drsimonj, 

Would you have any interest in adding DB support for `corralate()`?  I'll be glad to write the code and send you a PR, but wanted to first make sure that it fits your vision for this package.  

Thanks,

Edgar

**Comment by drsimonj** [comment]
Hi @edgararuiz ,

I didn't have this in mind, but don't see why not. It sounds like a very valuable addition to me!

Will be very happy to look over a PR if you get to it.

Simon

**Comment by drsimonj** [comment]
See #56
