### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [drsimonj/corrr#68]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _corrr_ package imports or suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. The errors seem to relate to a column named `rowname`. 

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding of the problem?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by edgararuiz** [comment]
Fixed by 6ab74a38d3ed70510730ccd3db17ab1dc912678c
