### ISSUE TITLE
Getting message about settings

### ISSUE THREAD

**Issue by ymer** [drsimonj/corrr#74]
I get the following message about specifications:
"Correlation method: 'pearson'
Missing treated using: 'pairwise.complete.obs'"

Even if I set those two inside correlate()

**Comment by edgararuiz** [comment]
Yes, it looks like it works like that by design.  If you wish to suppress the message, you can pass the `quiet` argument to `correlate()`.  That is shown in the second example in my reprex below.

``` r
x <- data.frame(x = 1:10, y = 1:10)
corrr::correlate(x)
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'
#> # A tibble: 2 x 3
#>   rowname     x     y
#>   <chr>   <dbl> <dbl>
#> 1 x          NA     1
#> 2 y           1    NA
corrr::correlate(x, quiet = TRUE)
#> # A tibble: 2 x 3
#>   rowname     x     y
#>   <chr>   <dbl> <dbl>
#> 1 x          NA     1
#> 2 y           1    NA
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
