### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by find19** [drsimonj/corrr#75]
Hi,
Wondering if you can help me find a couple of authors used this package. Also, if I use this package, how should I be citing it in the paper. Please advise…

**Comment by edgararuiz** [comment]
Hi, you can find citation verbiage of any package using the `citation()` function.  The one for this package throws an warning that I'll be looking into.  But the general info that I believe you need is there.  

Also, opening an issue in this repo is a good way of contacting the authors of this package.

``` r
citation("corrr")
#> Warning in citation("corrr"): no date field in DESCRIPTION file of package
#> 'corrr'
#> Warning in citation("corrr"): could not determine year for 'corrr' from
#> package DESCRIPTION file
#> 
#> To cite package 'corrr' in publications use:
#> 
#>   Simon Jackson, Jorge Cimentada and Edgar Ruiz (NA). corrr:
#>   Correlations in R. R package version 0.3.1.9000.
#>   https://github.com/drsimonj/corrr
#> 
#> A BibTeX entry for LaTeX users is
#> 
#>   @Manual{,
#>     title = {corrr: Correlations in R},
#>     author = {Simon Jackson and Jorge Cimentada and Edgar Ruiz},
#>     note = {R package version 0.3.1.9000},
#>     url = {https://github.com/drsimonj/corrr},
#>   }
#> 
#> ATTENTION: This citation information has been auto-generated from
#> the package DESCRIPTION file and may need manual editing, see
#> 'help("citation")'.
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
