### ISSUE TITLE
Create support for matrix class

### ISSUE THREAD

**Issue by drsimonj** [drsimonj/corrr#9]
If someone wants to submit something other than a cor_df (e.g., a square matrix) to any relevant functions, create default conditions that attempt to coerce the object to a cor_df (with new function as_cor_df), and then run the function.

**Comment by cimentadaj** [comment]
This should be closed, right? Because now there's `as_cordf` [here](https://github.com/drsimonj/corrr/blob/master/R/utility.R#L1-L35).

**Comment by drsimonj** [comment]
I suppose this is the case. I was thinking more that there would be a `.matrix` method that would attempt to coerce to `cor_df` for the user first. E.g., `shave()` only has a method for `cor_df`. But maybe someone wants to apply it to their correlation matrix. There could be a `.matrix` method that tries to coerce to cor_df, apply shave, and back to as_matrix.

Then again, as I'm thinking about it, this would be too much "behind the scenes" work. Better for user to explicitly handle this! Thanks for bumping the issue with this suggestion. I'll close it.
